# Generated by Django 4.2.3 on 2023-07-31 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('first_name', models.CharField(max_length=250, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=300, verbose_name='Apellidos')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empeados',
                'ordering': ['last_name', 'first_name', 'rfc'],
            },
        ),
    ]
