# Generated by Django 4.2.3 on 2023-08-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['country'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
