# Generated by Django 4.2.3 on 2023-08-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventories',
            options={'ordering': ['product', '-create_date', '-update_date'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.RenameField(
            model_name='inventories',
            old_name='create_dete',
            new_name='create_date',
        ),
    ]
