# Generated by Django 4.2.3 on 2023-08-02 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=45, verbose_name='Producto')),
                ('tradermark', models.CharField(max_length=45, verbose_name='Fabricante')),
                ('presentation', models.CharField(max_length=45, verbose_name='Presentacion')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('serial_number', models.CharField(max_length=45, verbose_name='Numero serial')),
                ('state', models.BooleanField(default=True, verbose_name='EStado')),
                ('crete_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificacion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='categories.categories', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['product', '-crete_date', '-update_date'],
            },
        ),
    ]
