# Generated by Django 4.2.3 on 2023-08-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product', '-create_date', '-update_date'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='created_by',
            new_name='create_by',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='crete_date',
            new_name='create_date',
        ),
    ]
